GET http://localhost:7000/
Accept: application/json

###

POST http://localhost:7000/doLogin
Content-Type: application/x-www-form-urlencoded

username=user&password=123

###

POST http://localhost:7000/doLogin
Content-Type: application/json

{
  "username": "user",
  "password": "123"
}

###